version: "3.8"

services:
  # Redis Database
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - todo-net
    command: redis-server --appendonly yes

  # Todo Service
  todo-service:
    build:
      context: ./todo
      dockerfile: Dockerfile
    container_name: todo-service
    ports:
      - "8001:8000"
    networks:
      - todo-net
    environment:
      - TODO_NOTIFICATION_ENDPOINT=http://todo-notification-service:9000/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: python -m uvicorn --host=0.0.0.0 --port=8000 todo.main:app

  # Todo Notification Service
  todo-notification-service:
    build:
      context: ./todo-notification
      dockerfile: Dockerfile
    container_name: todo-notification-service
    ports:
      - "9000:9000"
    networks:
      - todo-net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: python -m uvicorn --host=0.0.0.0 --port=9000 notification.main:app

  # Todo Web Application
  todo-webapp:
    build:
      context: ./todo-webapp
      dockerfile: Dockerfile
    container_name: todo-webapp
    ports:
      - "3000:3000"
    networks:
      - todo-net
    environment:
      - REACT_APP_TODO_ENDPOINT=http://localhost:8000/todo/
      - REACT_APP_NOTIFICATION_ENDPOINT=http://localhost:8000/notification/
      - CI=false
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api-gateway
    stdin_open: true
    tty: true

  # API Gateway (NGINX)
  api-gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    networks:
      - todo-net
    depends_on:
      - todo-service
      - todo-notification-service

networks:
  todo-net:
    driver: bridge
